var annotated_dup =
[
    [ "Birdy3d", null, [
      [ "core", null, [
        [ "Application", "classBirdy3d_1_1core_1_1Application.html", null ],
        [ "Input", "classBirdy3d_1_1core_1_1Input.html", null ],
        [ "Logger", "classBirdy3d_1_1core_1_1Logger.html", null ],
        [ "ResourceHandle", "classBirdy3d_1_1core_1_1ResourceHandle.html", null ],
        [ "ResourceIdentifier", "classBirdy3d_1_1core_1_1ResourceIdentifier.html", null ],
        [ "ResourceManager", "classBirdy3d_1_1core_1_1ResourceManager.html", null ]
      ] ],
      [ "ecs", null, [
        [ "Component", "classBirdy3d_1_1ecs_1_1Component.html", "classBirdy3d_1_1ecs_1_1Component" ],
        [ "Entity", "classBirdy3d_1_1ecs_1_1Entity.html", null ],
        [ "Scene", "classBirdy3d_1_1ecs_1_1Scene.html", null ],
        [ "Transform3d", "classBirdy3d_1_1ecs_1_1Transform3d.html", null ]
      ] ],
      [ "events", null, [
        [ "CollisionEvent", "classBirdy3d_1_1events_1_1CollisionEvent.html", null ],
        [ "Event", "classBirdy3d_1_1events_1_1Event.html", null ],
        [ "EventBus", "classBirdy3d_1_1events_1_1EventBus.html", null ],
        [ "FunctionHandler", "classBirdy3d_1_1events_1_1FunctionHandler.html", null ],
        [ "HandlerFunctionBase", "classBirdy3d_1_1events_1_1HandlerFunctionBase.html", null ],
        [ "InputCharEvent", "classBirdy3d_1_1events_1_1InputCharEvent.html", null ],
        [ "InputClickEvent", "classBirdy3d_1_1events_1_1InputClickEvent.html", null ],
        [ "InputKeyEvent", "classBirdy3d_1_1events_1_1InputKeyEvent.html", null ],
        [ "InputScrollEvent", "classBirdy3d_1_1events_1_1InputScrollEvent.html", null ],
        [ "MemberFunctionHandler", "classBirdy3d_1_1events_1_1MemberFunctionHandler.html", null ],
        [ "ResourceLoadEvent", "classBirdy3d_1_1events_1_1ResourceLoadEvent.html", null ],
        [ "TransformChangedEvent", "classBirdy3d_1_1events_1_1TransformChangedEvent.html", null ],
        [ "WindowResizeEvent", "classBirdy3d_1_1events_1_1WindowResizeEvent.html", null ]
      ] ],
      [ "physics", null, [
        [ "Collider", "classBirdy3d_1_1physics_1_1Collider.html", null ],
        [ "ColliderComponent", "classBirdy3d_1_1physics_1_1ColliderComponent.html", "classBirdy3d_1_1physics_1_1ColliderComponent" ],
        [ "Collision", "classBirdy3d_1_1physics_1_1Collision.html", null ],
        [ "CollisionMesh", "classBirdy3d_1_1physics_1_1CollisionMesh.html", null ],
        [ "CollisionPoints", "classBirdy3d_1_1physics_1_1CollisionPoints.html", null ],
        [ "CollisionShape", "classBirdy3d_1_1physics_1_1CollisionShape.html", null ],
        [ "CollisionSphere", "classBirdy3d_1_1physics_1_1CollisionSphere.html", null ],
        [ "ConvexMeshGenerators", "classBirdy3d_1_1physics_1_1ConvexMeshGenerators.html", null ],
        [ "IntermediateMesh", "classBirdy3d_1_1physics_1_1IntermediateMesh.html", null ],
        [ "Mesh", "structBirdy3d_1_1physics_1_1Mesh.html", null ],
        [ "PhysicsWorld", "classBirdy3d_1_1physics_1_1PhysicsWorld.html", null ],
        [ "Triangle", "structBirdy3d_1_1physics_1_1Triangle.html", "structBirdy3d_1_1physics_1_1Triangle" ]
      ] ],
      [ "render", null, [
        [ "Camera", "classBirdy3d_1_1render_1_1Camera.html", null ],
        [ "DirectionalLight", "classBirdy3d_1_1render_1_1DirectionalLight.html", null ],
        [ "Material", "classBirdy3d_1_1render_1_1Material.html", null ],
        [ "Mesh", "classBirdy3d_1_1render_1_1Mesh.html", null ],
        [ "Model", "classBirdy3d_1_1render_1_1Model.html", null ],
        [ "ModelComponent", "classBirdy3d_1_1render_1_1ModelComponent.html", null ],
        [ "PointLight", "classBirdy3d_1_1render_1_1PointLight.html", null ],
        [ "Rendertarget", "classBirdy3d_1_1render_1_1Rendertarget.html", null ],
        [ "Shader", "classBirdy3d_1_1render_1_1Shader.html", null ],
        [ "Spotlight", "classBirdy3d_1_1render_1_1Spotlight.html", null ],
        [ "Texture", "classBirdy3d_1_1render_1_1Texture.html", null ],
        [ "Vertex", "structBirdy3d_1_1render_1_1Vertex.html", null ]
      ] ],
      [ "serializer", null, [
        [ "Adapter", "classBirdy3d_1_1serializer_1_1Adapter.html", null ],
        [ "Array", "structBirdy3d_1_1serializer_1_1Array.html", null ],
        [ "BaseRegister", "structBirdy3d_1_1serializer_1_1BaseRegister.html", null ],
        [ "Bool", "structBirdy3d_1_1serializer_1_1Bool.html", null ],
        [ "DerivedRegister", "structBirdy3d_1_1serializer_1_1DerivedRegister.html", null ],
        [ "Generator", "classBirdy3d_1_1serializer_1_1Generator.html", null ],
        [ "JsonParser", "classBirdy3d_1_1serializer_1_1JsonParser.html", null ],
        [ "MinimalJsonGenerator", "classBirdy3d_1_1serializer_1_1MinimalJsonGenerator.html", null ],
        [ "Null", "structBirdy3d_1_1serializer_1_1Null.html", null ],
        [ "Number", "structBirdy3d_1_1serializer_1_1Number.html", null ],
        [ "Object", "structBirdy3d_1_1serializer_1_1Object.html", null ],
        [ "ParseError", "classBirdy3d_1_1serializer_1_1ParseError.html", null ],
        [ "Parser", "classBirdy3d_1_1serializer_1_1Parser.html", null ],
        [ "PointerRegistry", "classBirdy3d_1_1serializer_1_1PointerRegistry.html", null ],
        [ "PrettyJsonGenerator", "classBirdy3d_1_1serializer_1_1PrettyJsonGenerator.html", null ],
        [ "ReflectClass", "classBirdy3d_1_1serializer_1_1ReflectClass.html", null ],
        [ "ReflectMember", "structBirdy3d_1_1serializer_1_1ReflectMember.html", null ],
        [ "Reflector", "classBirdy3d_1_1serializer_1_1Reflector.html", null ],
        [ "Serializer", "classBirdy3d_1_1serializer_1_1Serializer.html", null ],
        [ "String", "structBirdy3d_1_1serializer_1_1String.html", null ]
      ] ],
      [ "ui", null, [
        [ "AbsoluteLayout", "classBirdy3d_1_1ui_1_1AbsoluteLayout.html", "classBirdy3d_1_1ui_1_1AbsoluteLayout" ],
        [ "Button", "classBirdy3d_1_1ui_1_1Button.html", "classBirdy3d_1_1ui_1_1Button" ],
        [ "Canvas", "classBirdy3d_1_1ui_1_1Canvas.html", null ],
        [ "Character", "structBirdy3d_1_1ui_1_1Character.html", null ],
        [ "CharEvent", "classBirdy3d_1_1ui_1_1CharEvent.html", null ],
        [ "CheckBox", "classBirdy3d_1_1ui_1_1CheckBox.html", "classBirdy3d_1_1ui_1_1CheckBox" ],
        [ "ClickEvent", "classBirdy3d_1_1ui_1_1ClickEvent.html", null ],
        [ "CollapsibleContainer", "classBirdy3d_1_1ui_1_1CollapsibleContainer.html", "classBirdy3d_1_1ui_1_1CollapsibleContainer" ],
        [ "Console", "classBirdy3d_1_1ui_1_1Console.html", null ],
        [ "ConsoleCommands", "classBirdy3d_1_1ui_1_1ConsoleCommands.html", null ],
        [ "Container", "classBirdy3d_1_1ui_1_1Container.html", null ],
        [ "ContextItem", "classBirdy3d_1_1ui_1_1ContextItem.html", null ],
        [ "ContextMenu", "classBirdy3d_1_1ui_1_1ContextMenu.html", null ],
        [ "Dimension", "classBirdy3d_1_1ui_1_1Dimension.html", null ],
        [ "DimRect", "classBirdy3d_1_1ui_1_1DimRect.html", null ],
        [ "DirectionalLayout", "classBirdy3d_1_1ui_1_1DirectionalLayout.html", "classBirdy3d_1_1ui_1_1DirectionalLayout" ],
        [ "DropEvent", "classBirdy3d_1_1ui_1_1DropEvent.html", null ],
        [ "DynamicGridLayout", "classBirdy3d_1_1ui_1_1DynamicGridLayout.html", "classBirdy3d_1_1ui_1_1DynamicGridLayout" ],
        [ "EntityTreeModel", "classBirdy3d_1_1ui_1_1EntityTreeModel.html", null ],
        [ "FocusEvent", "classBirdy3d_1_1ui_1_1FocusEvent.html", null ],
        [ "FocusLostEvent", "classBirdy3d_1_1ui_1_1FocusLostEvent.html", null ],
        [ "FPSCounter", "classBirdy3d_1_1ui_1_1FPSCounter.html", null ],
        [ "KeyEvent", "classBirdy3d_1_1ui_1_1KeyEvent.html", null ],
        [ "Label", "classBirdy3d_1_1ui_1_1Label.html", "classBirdy3d_1_1ui_1_1Label" ],
        [ "Layout", "classBirdy3d_1_1ui_1_1Layout.html", "classBirdy3d_1_1ui_1_1Layout" ],
        [ "MaxLayout", "classBirdy3d_1_1ui_1_1MaxLayout.html", "classBirdy3d_1_1ui_1_1MaxLayout" ],
        [ "MenuBar", "classBirdy3d_1_1ui_1_1MenuBar.html", null ],
        [ "MouseEnterEvent", "classBirdy3d_1_1ui_1_1MouseEnterEvent.html", null ],
        [ "MouseLeaveEvent", "classBirdy3d_1_1ui_1_1MouseLeaveEvent.html", null ],
        [ "NumberInput", "classBirdy3d_1_1ui_1_1NumberInput.html", "classBirdy3d_1_1ui_1_1NumberInput" ],
        [ "OpenGLPainter", "classBirdy3d_1_1ui_1_1OpenGLPainter.html", null ],
        [ "Painter", "classBirdy3d_1_1ui_1_1Painter.html", null ],
        [ "Position", "classBirdy3d_1_1ui_1_1Position.html", null ],
        [ "Rect", "classBirdy3d_1_1ui_1_1Rect.html", null ],
        [ "Rectangle", "classBirdy3d_1_1ui_1_1Rectangle.html", null ],
        [ "ResizeEvent", "classBirdy3d_1_1ui_1_1ResizeEvent.html", null ],
        [ "Scrollable", "classBirdy3d_1_1ui_1_1Scrollable.html", null ],
        [ "ScrollContainer", "classBirdy3d_1_1ui_1_1ScrollContainer.html", null ],
        [ "ScrollEvent", "classBirdy3d_1_1ui_1_1ScrollEvent.html", null ],
        [ "Shape", "classBirdy3d_1_1ui_1_1Shape.html", "classBirdy3d_1_1ui_1_1Shape" ],
        [ "Size", "classBirdy3d_1_1ui_1_1Size.html", null ],
        [ "StaticGridLayout", "classBirdy3d_1_1ui_1_1StaticGridLayout.html", "classBirdy3d_1_1ui_1_1StaticGridLayout" ],
        [ "Text", "classBirdy3d_1_1ui_1_1Text.html", null ],
        [ "TextDescription", "classBirdy3d_1_1ui_1_1TextDescription.html", "classBirdy3d_1_1ui_1_1TextDescription" ],
        [ "TextField", "classBirdy3d_1_1ui_1_1TextField.html", null ],
        [ "TextRenderer", "classBirdy3d_1_1ui_1_1TextRenderer.html", null ],
        [ "TextVertex", "structBirdy3d_1_1ui_1_1TextVertex.html", null ],
        [ "Theme", "classBirdy3d_1_1ui_1_1Theme.html", null ],
        [ "TreeItem", "classBirdy3d_1_1ui_1_1TreeItem.html", null ],
        [ "TreeItemPosition", "structBirdy3d_1_1ui_1_1TreeItemPosition.html", null ],
        [ "TreeModel", "classBirdy3d_1_1ui_1_1TreeModel.html", null ],
        [ "TreeView", "classBirdy3d_1_1ui_1_1TreeView.html", null ],
        [ "UIEvent", "classBirdy3d_1_1ui_1_1UIEvent.html", null ],
        [ "Widget", "classBirdy3d_1_1ui_1_1Widget.html", "classBirdy3d_1_1ui_1_1Widget" ],
        [ "Window", "classBirdy3d_1_1ui_1_1Window.html", null ],
        [ "WindowSnapArea", "classBirdy3d_1_1ui_1_1WindowSnapArea.html", "classBirdy3d_1_1ui_1_1WindowSnapArea" ]
      ] ],
      [ "utils", null, [
        [ "Color", "classBirdy3d_1_1utils_1_1Color.html", null ],
        [ "FPPlayerController", "classBirdy3d_1_1utils_1_1FPPlayerController.html", null ],
        [ "Identifier", "classBirdy3d_1_1utils_1_1Identifier.html", null ],
        [ "PrimitiveGenerator", "classBirdy3d_1_1utils_1_1PrimitiveGenerator.html", null ],
        [ "Unicode", "classBirdy3d_1_1utils_1_1Unicode.html", null ]
      ] ]
    ] ],
    [ "fmt", null, [
      [ "formatter< Birdy3d::ui::Rect >", "structfmt_1_1formatter_3_01Birdy3d_1_1ui_1_1Rect_01_4.html", null ],
      [ "formatter< Birdy3d::utils::Color >", "structfmt_1_1formatter_3_01Birdy3d_1_1utils_1_1Color_01_4.html", null ],
      [ "formatter< EventType >", "structfmt_1_1formatter_3_01EventType_01_4.html", null ],
      [ "formatter< glm::vec< L, T > >", "structfmt_1_1formatter_3_01glm_1_1vec_3_01L_00_01T_01_4_01_4.html", null ]
    ] ],
    [ "Channel", "classChannel.html", null ]
];