name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build-linux-x11:
    runs-on: ubuntu-latest

    env:
      CC: gcc-10
      CXX: g++-10

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libgl-dev
        sudo apt install libassimp-dev ccache

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G 'Unix Makefiles'

    - name: Build
      run: cmake --build ${{github.workspace}}/build --target Birdy3d_engine Birdy3d_sandbox -- -j4

    - name: Check Executable
      run: test -f build/out/bin/Birdy3d_sandbox

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G 'Visual Studio 17 2022'

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target Birdy3d_engine Birdy3d_sandbox

    - name: Check Executable
      shell: bash
      run: test -f build/out/bin/Birdy3d_sandbox.exe
