name: Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install Doxygen 1.9.6
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz libclang-cpp14 libclang1-14
        wget https://www.doxygen.nl/files/doxygen-1.9.6.linux.bin.tar.gz
        tar -xvzf doxygen-1.9.6.linux.bin.tar.gz
        ln -s doxygen-1.9.6/bin/doxygen doxygen

    - name: Build
      run: |
        mkdir build
        ./doxygen

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/docs/html
